version: '3.8'

services:
  app:
    # حاوية Apache + PHP
    image: mcr.microsoft.com/vscode/devcontainers/php:8.1-ubuntu
    volumes:
      - ..:/workspace:cached   # يربط جذر المستودع بحاوية العمل
    working_dir: /workspace    # مجلّد العمل داخل الحاوية
    ports:
      - "80:80"                # يعيد توجيه المنفذ 80 من الحاوية إلى Codespace
    depends_on:
      - db                     # يضمن تشغيل قاعدة البيانات أولًا

  db:
    # حاوية MySQL
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpass   # كلمة مرور الروت (غيّرها)
      MYSQL_DATABASE:  mydatabase     # اسم القاعدة الافتراضي (غيّره)
      MYSQL_USER:      devuser        # مستخدم جديد (غيّره)
      MYSQL_PASSWORD:  devpass        # كلمة مرور المستخدم (غيّره)
    volumes:
      - db_data:/var/lib/mysql        # تخزين دائم للبيانات
    ports:
      - "3306:3306"                   # يمكن توجيهه أيضاً إن احتجت

volumes:
  db_data:                           # تعريف volume خارجي لتثبيت البيانات

