version: '3.8'

services:
  app:
    # حاوية Apache + PHP
    image: mcr.microsoft.com/vscode/devcontainers/php:8.1-ubuntu
    # ربط مجلد src داخل الريبو بـ DocumentRoot في أباتشي
    volumes:
      - ../src:/var/www/html:cached
    working_dir: /var/www/html
    ports:
      - "80:80"
    depends_on:
      - db

  db:
    # حاوية MySQL
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpass   # غيّرها إذا أحببت
      MYSQL_DATABASE:  mydatabase     # غيّر اسم القاعدة
      MYSQL_USER:      devuser        # غيّر اسم المستخدم
      MYSQL_PASSWORD:  devpass        # غيّر كلمة المرور
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db_data:
