
version: '3.8'

services:
  app:
    image: mcr.microsoft.com/vscode/devcontainers/php:8.1-ubuntu
    # ربط مجلد الكود بـ DocumentRoot
    volumes:
      - ../src:/var/www/html:cached
    working_dir: /var/www/html
    ports:
      - "80:80"
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE:  mydatabase
      MYSQL_USER:      devuser
      MYSQL_PASSWORD:  devpass
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db_data:
